digit = input()
digit = digit.split(' ')
digit = ''.join(digit)
digit = int(digit)
print(type(digit))
# item['price'] = item['price'].split(' ')
#         item['price'] = ''.join('')
#         item['price'] = filter(lambda x: x.isdigit(), item['price'])
#         item['price'] = int(item['price'])

